name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions: write-all

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          yarn
          yarn run build

      - name: Deploy preview
        uses: ACCESS-NRI/pr-preview-action@v1
        with:
          source-dir: ./public/
          preview-branch: preview
